# Generated by Django 5.0.4 on 2024-05-02 13:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.FileField(upload_to='')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RiddleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('web', 'WEB'), ('line', 'LINE')], max_length=10)),
                ('time', models.CharField(choices=[('10', '〜15分'), ('30', '15分〜45分'), ('60', '45分〜90分'), ('120', '90分〜180分'), ('300', '180分〜')], max_length=10)),
                ('level', models.CharField(choices=[('1', '初級'), ('2', '中級'), ('3', '上級')], max_length=10)),
                ('rating', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_story', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_gimmick', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_sukkiri', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_level', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('release_date', models.DateField()),
                ('end_date', models.DateField()),
                ('url', models.CharField(max_length=255)),
                ('playings', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateField()),
                ('bookmarks', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='ブックマークユーザー')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.creatormodel')),
            ],
        ),
    ]
