# Generated by Django 5.0.6 on 2024-05-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_riddlemodel_rating_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riddlemodel',
            name='rating_level',
            field=models.CharField(choices=[('1', '初級'), ('2', '初中級'), ('3', '中級'), ('4', '上級'), ('5', '超上級')], max_length=10),
        ),
        migrations.AlterField(
            model_name='riddlemodel',
            name='rating_quantity',
            field=models.CharField(choices=[('1', '〜15分'), ('2', '15分〜45分'), ('3', '45分〜90分'), ('4', '90分~180分'), ('5', '180分〜')], max_length=10),
        ),
    ]
