# Generated by Django 5.0.6 on 2024-05-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_riddlemodel_rating_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riddlemodel',
            old_name='rating_level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='riddlemodel',
            old_name='rating_quantity',
            new_name='time',
        ),
    ]
