# Generated by Django 5.0.6 on 2024-06-20 11:16

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_riddlemodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='riddlemodel',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riddlemodel',
            name='review',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
