# Generated by Django 5.0.6 on 2024-06-23 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_articlemodel_riddles'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='riddle_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.riddlemodel', verbose_name='謎1'),
        ),
    ]
