# Generated by Django 5.0.6 on 2024-06-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_articlemodel_riddle_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='riddle_1',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='riddles',
            field=models.ManyToManyField(blank=True, to='api.riddlemodel', verbose_name='紹介謎'),
        ),
    ]
