# Generated by Django 5.0.6 on 2024-07-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_articlemodel_riddle_1_articlemodel_riddles'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
